language: node_js
node_js:
- '6'
script:
- sh scripts/coverage.sh
deploy:
  provider: npm
  email: ben@ajaxscape.com
  api_key:
    secure: fK3rq2HfnnFP7BrEhqdp0TREqJIpM8SE9pe8d+g/IJFsQ2ANqXaVZ/uwunr9G+7iuJy53dWUxONpvVXhGXiDfRzWAeXIkCcZjjRF9hO0waHYwHo1k69o7MJNzYI0A7s2ZqExR2MyXjHjhDY5jNibls/fXihyZhhfyv19oNaCZ80/Tm7Olp6eappIwZ+eAvaKIh+JG/ohsLIa9Mzg2qeZTccuLZotXIKNlDhuYxiX7LBAzEpcG2o5ybhInr4RERn3EXW9Z7eKgqIhaie4C0CBuZkyuSpAfKdDUd6dHPg/3tOqMJNrT6tv8mRIYcsmk1vKj9oMqFyeEAgxQ0Mjff5kMdXd76R5fqulKOLD5oU49mFPKx+AavE/iy8sp8PLhzLoOiw5A68eTf44i9d5HYRvsA/S/4k0oyNIawFicp+y2k/ZsJHIWWKmgdwkTroxsN8TROwS1vcP7mmS4b7NZY0JnxzsWunLtv/ojoRsmv8KWoHbWcjnXUhvkj4abZU051CBy33z7NIGH37c3ufn7MzzsZtQFLBuBqnaCZ/hfHtsReTp2cYmvNNZbrMIIxTXRS/2p8CH6pRzqif8+/MTXBRSYdoD0xOHGWswPz2JSwQ5glwkeG43OVc6q5OL63n9wi+ribCNlacFZ8nrxvSXYX8Au4mY9s3auUZNmKsIh3+zLuw=
  on:
    repo: ajaxscape/tamarin
    branch: master